/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my;

import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Harshit
 */
public class EntryUI extends javax.swing.JFrame {

    /**
     * Creates new form EntryUI
     */
    private final Toolkit tk;
    private File dna,img;
    private BufferedImage image;
    private JFileChooser fc1,fc2;
    public EntryUI() {
        initComponents();
        tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        super.setSize(xsize,ysize);
        dna = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        imagearea = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jTextField1.setBackground(new java.awt.Color(240, 240, 240));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(190, 120, 540, 35);

        jTextField2.setBackground(new java.awt.Color(240, 240, 240));
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setText("House/Door No.");
        jTextField2.setToolTipText("");
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(190, 210, 370, 40);

        jTextField3.setBackground(new java.awt.Color(240, 240, 240));
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField3.setText("Village/Town/City");
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(590, 260, 370, 40);

        jTextField4.setBackground(new java.awt.Color(240, 240, 240));
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField4.setText("Street/Road/Lane");
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(590, 210, 370, 40);

        jTextField5.setBackground(new java.awt.Color(240, 240, 240));
        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField5.setText("Area/Locality/Sector");
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(190, 260, 370, 40);

        jTextField6.setBackground(new java.awt.Color(240, 240, 240));
        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField6.setText("District");
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField6MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(190, 310, 370, 40);

        jTextField7.setBackground(new java.awt.Color(240, 240, 240));
        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField7.setText("State");
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField7MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(590, 310, 370, 40);

        jTextField8.setBackground(new java.awt.Color(240, 240, 240));
        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField8);
        jTextField8.setBounds(190, 380, 130, 40);

        jTextField9.setBackground(new java.awt.Color(240, 240, 240));
        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jTextField9);
        jTextField9.setBounds(460, 380, 360, 40);

        jTextField10.setBackground(new java.awt.Color(240, 240, 240));
        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField10KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField10);
        jTextField10.setBounds(1090, 380, 260, 40);

        jTextField11.setBackground(new java.awt.Color(240, 240, 240));
        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField11KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField11);
        jTextField11.setBounds(190, 490, 380, 40);

        jTextField12.setBackground(new java.awt.Color(240, 240, 240));
        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField12.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField12KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField12);
        jTextField12.setBounds(860, 490, 250, 40);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setMaximumRowCount(3);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHER" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(190, 160, 130, 40);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guardian", "Father", "Mother", "Husband", "Wife" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(190, 440, 180, 40);

        dateChooserCombo1.setCalendarPreferredSize(new java.awt.Dimension(350, 300));
        dateChooserCombo1.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);
        try {
            dateChooserCombo1.setDefaultPeriods(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar(1991, 0, 1),
                new java.util.GregorianCalendar(1991, 0, 1))));
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }
    dateChooserCombo1.setFieldFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    dateChooserCombo1.setNavigateFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 11));
    jPanel1.add(dateChooserCombo1);
    dateChooserCombo1.setBounds(480, 160, 180, 40);

    jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jButton1.setText("Get Image");
    jPanel1.add(jButton1);
    jButton1.setBounds(30, 690, 160, 30);

    jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jButton2.setText("Get Image");
    jPanel1.add(jButton2);
    jButton2.setBounds(330, 690, 160, 30);

    jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jButton3.setText("Get FIle");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton3);
    jButton3.setBounds(600, 690, 160, 30);

    jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jButton4.setText("Submit");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton4);
    jButton4.setBounds(1090, 630, 150, 40);

    jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jButton5.setText("Clear");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton5);
    jButton5.setBounds(1000, 710, 150, 40);

    jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jButton6.setText("Get Image");
    jButton6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton6ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton6);
    jButton6.setBounds(1150, 300, 200, 23);

    jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jButton7.setText("Logout");
    jButton7.setToolTipText("");
    jButton7.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton7ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton7);
    jButton7.setBounds(1200, 710, 150, 40);

    imagearea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    imagearea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.lightGray, null, null));
    jPanel1.add(imagearea);
    imagearea.setBounds(1150, 100, 200, 200);

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/UPLOAD.jpg"))); // NOI18N
    jLabel1.setText("jLabel1");
    jPanel1.add(jLabel1);
    jLabel1.setBounds(0, 0, 1370, 770);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you sure?", "Logout",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            new LoginUI().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char ch = evt.getKeyChar();
        if(!(Character.isLetter(evt.getKeyChar())) && (ch != ' '))
            evt.consume();
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyTyped
        if(!(Character.isDigit(evt.getKeyChar())) || (jTextField8.getText().length()>=6))
            evt.consume();
    }//GEN-LAST:event_jTextField8KeyTyped

    private void jTextField10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyTyped
        if(!(Character.isDigit(evt.getKeyChar())) || (jTextField10.getText().length()>=10))
            evt.consume();
    }//GEN-LAST:event_jTextField10KeyTyped

    private void jTextField12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyTyped
        if(!(Character.isDigit(evt.getKeyChar())) || (jTextField12.getText().length()>=12))
            evt.consume();
    }//GEN-LAST:event_jTextField12KeyTyped

    private void jTextField11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyTyped
        if(!(Character.isLetter(evt.getKeyChar())) && (evt.getKeyChar() != ' ')){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField11KeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            if(jTextField1.getText().isEmpty() || jTextField2.getText().equals("House/Door No.") || jTextField2.getText().isEmpty()
                    || jTextField3.getText().equals("Village/Town/City") || jTextField3.getText().isEmpty() || 
                    jTextField4.getText().equals("Street/Road/Lane") || jTextField4.getText().isEmpty()
                    || jTextField5.getText().equals("Area/Locality/Sector") ||jTextField5.getText().isEmpty() || 
                    jTextField6.getText().equals("District") || jTextField6.getText().isEmpty()
                    || jTextField7.getText().equals("State") || jTextField7.getText().isEmpty() || 
                    jTextField8.getText().isEmpty() || jTextField9.getText().isEmpty()
                    || jTextField10.getText().isEmpty() || jTextField11.getText().isEmpty() || jTextField12.getText().isEmpty()
                    ||jTextField8.getText().length() != 6 || jTextField10.getText().length() != 10
                    || jTextField12.getText().length() != 12 || !dna.exists() || !img.exists()){
                JOptionPane.showMessageDialog(this, "One or more fields are empty or incorrect!", "Submit", JOptionPane.WARNING_MESSAGE);
            }
            else{
                String name = jTextField1.getText();
                String gender = (String)jComboBox1.getSelectedItem();
                String date = dateChooserCombo1.getText();
                String add1 = jTextField2.getText();
                String add2 = jTextField4.getText();
                String add3 = jTextField5.getText();
                String add4 = jTextField3.getText();
                String add5 = jTextField6.getText();
                String add6 = jTextField7.getText();
                int pin = Integer.parseInt(jTextField8.getText());
                String eid = jTextField9.getText();
                long mobno = Long.parseLong(jTextField10.getText());
                String co = (String)jComboBox2.getSelectedItem();
                String coname = jTextField11.getText();
                long coadhno = Long.parseLong(jTextField12.getText());
                long adhno = genadhno();
                try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    try(Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:ORCL","SYSTEM","Harshit123")){
                        PreparedStatement ps = con.prepareStatement("insert into aadhar values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                        try(FileInputStream fin1 = new FileInputStream(img)){
                            ps.setLong(1, adhno);
                            ps.setString(2, name);
                            ps.setString(3, gender);
                            ps.setString(4, date);
                            ps.setInt(5, pin);
                            ps.setString(6, eid);
                            ps.setLong(7, mobno);
                            ps.setString(8, co);
                            ps.setString(9, coname);
                            ps.setLong(10, coadhno);
                            ps.setBinaryStream(11, fin1, fin1.available());
                            Reader fr = new FileReader(dna);
                            ps.setCharacterStream(12, fr, (int)dna.length());
                            ps.setString(13, add1);
                            ps.setString(14, add2);
                            ps.setString(15, add3);
                            ps.setString(16, add4);
                            ps.setString(17, add5);
                            ps.setString(18, add6);
                            ps.executeUpdate();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(this,"Server Error!","Error!",JOptionPane.ERROR_MESSAGE);
                        }
                        JOptionPane.showMessageDialog(this,"Data updated successfully!\nYour AADHAAR NO. is: "+adhno,"Success!",JOptionPane.INFORMATION_MESSAGE);
                        jButton5.doClick();
                    }catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this,"Server Error!","Error!",JOptionPane.ERROR_MESSAGE);
                    }
                }catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(this,"Driver Error!","Error!",JOptionPane.ERROR_MESSAGE);
                }
            }
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, "Please enter correct DNA file or Image!", "Submit", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        fc1 = new JFileChooser();
        fc1.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc1.addChoosableFileFilter(new FileNameExtensionFilter("DNA File", "fasta"));
        fc1.setAcceptAllFileFilterUsed(false);
        int result = fc1.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION)
            dna = fc1.getSelectedFile();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        jTextField4.setText("");
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        jTextField5.setText("");
    }//GEN-LAST:event_jTextField5MouseClicked

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        jTextField3.setText("");
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseClicked
        jTextField6.setText("");
    }//GEN-LAST:event_jTextField6MouseClicked

    private void jTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseClicked
        jTextField7.setText("");
    }//GEN-LAST:event_jTextField7MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        fc2 = new JFileChooser();
        fc2.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc2.addChoosableFileFilter(new FileNameExtensionFilter("Images", "jpg", "png", "gif", "bmp"));
        fc2.setAcceptAllFileFilterUsed(false);
        int result = fc2.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION)
            img = fc2.getSelectedFile();
        try {
            image = ImageIO.read(img);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Invalid image!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        ImageIcon icon =new ImageIcon(image);
        imagearea.setIcon(icon);
    }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        jTextField1.setText("");
        jTextField2.setText("House/Door No.");
        jTextField3.setText("Village/Town/City");
        jTextField4.setText("Street/Road/Lane");
        jTextField5.setText("Area/Locality/Sector");
        jTextField6.setText("District");
        jTextField7.setText("State");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        dna = null;
        image = null;
        img = null;
        imagearea.setIcon(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EntryUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JLabel imagearea;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    private long genadhno() {
        Random rand = new Random();
        char[] digits = new char[12];
        digits[0] = (char) (rand.nextInt(9)+'1');
        for(int i = 1; i < 12; i++)
            digits[i] = (char) (rand.nextInt(10)+'0');
        return Long.parseLong(new String(digits));
    }

}
